apiVersion: v1
kind: ReplicationController
metadata:
  name: tongwei
spec:
  replicas: 3
  selector:
    app: tongwei
  template:
    metadata:
      labels:
        app: tongwei
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: tongwei
          image: tongweidocker/k8sinaction:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
