apiVersion: v1
kind: Pod
metadata:
  name: tongwei-v2
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
  - name: tongwei
    image: tongweidocker/k8sinaction:1.0
    ports:
      - containerPort: 8080