apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc # need it when using the claim as pod's volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""