apiVersion: v1
kind: Pod
metadata:
  name: gitrepo-volume-pod
  labels:
    app: tongwei
spec:
  initContainers:
    - name: git-clone
      image: alpine/git
      args:
        - clone
        - --single-branch
        - --
        - https://github.com/tongweiz/kubia-website-example.git
        - /repo
      volumeMounts:
        - mountPath: /repo
          name: html
  containers:
    - name: web-server
      image: nginx:alpine
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
          readOnly: true
      ports:
        - containerPort: 80
          protocol: TCP
  volumes:
    - name: html
      emptyDir: {}