apiVersion: v1
kind: ReplicationController
metadata:
  name: tongwei
spec:
  replicas: 3
  selector:
    app: tongwei
  template:
    metadata:
      labels:
        app: tongwei
    spec:
      containers:
        - name: tongwei
          image: tongweidocker/k8sinaction:1.0
          ports:
            - containerPort: 8080
